# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Will Huang
# Description of the Site
description: Welcome to my page! I'm glad you're here.
description-sub: You can scroll down to learn more about me and use the "More" drop down to find my research and resume.
# URL of Image of the Site
# site-image: 
# Keywords of the Site
# site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
# favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/eiffel-underup.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: wh629@nyu.edu
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: williamhuang93
github_username:  wh629
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: Will Huang

# Name of the Author
author-name: Will Huang
# URL for the Image of the Author
author-image: /assets/images/will-huang.jpg
# 60 Words About the Author
author-about-long:
author-about-short: Researcher - Data Scientist - Boardgame Enthusiast - Food Lover
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/williamhuang93/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
